environment:
  MYSQL_DATABASE: node_mysql
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!

  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install

before_test:
  - "SET PATH=C:\Program Files\MySQL\MySQL Server 5.6\bin;%PATH%"
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create %MYSQL_DATABASE%

build: off

services:
  - mysql

test_script:
  - mysql --version
  - node --version
  - npm --version
  - npm run test-ci

version: "{build}"
